{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "1d28621a-34e9-49e3-8460-13e5d9b2c52d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Raw dataset loaded successfully\n",
      "Raw dataset shape: (525461, 8)\n",
      "Columns in dataset:\n",
      "['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'Price', 'Customer ID', 'Country']\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Invoice</th>\n",
       "      <th>StockCode</th>\n",
       "      <th>Description</th>\n",
       "      <th>Quantity</th>\n",
       "      <th>InvoiceDate</th>\n",
       "      <th>Price</th>\n",
       "      <th>Customer ID</th>\n",
       "      <th>Country</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>489434</td>\n",
       "      <td>85048</td>\n",
       "      <td>15CM CHRISTMAS GLASS BALL 20 LIGHTS</td>\n",
       "      <td>12</td>\n",
       "      <td>2009-12-01 07:45:00</td>\n",
       "      <td>6.95</td>\n",
       "      <td>13085.0</td>\n",
       "      <td>United Kingdom</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>489434</td>\n",
       "      <td>79323P</td>\n",
       "      <td>PINK CHERRY LIGHTS</td>\n",
       "      <td>12</td>\n",
       "      <td>2009-12-01 07:45:00</td>\n",
       "      <td>6.75</td>\n",
       "      <td>13085.0</td>\n",
       "      <td>United Kingdom</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>489434</td>\n",
       "      <td>79323W</td>\n",
       "      <td>WHITE CHERRY LIGHTS</td>\n",
       "      <td>12</td>\n",
       "      <td>2009-12-01 07:45:00</td>\n",
       "      <td>6.75</td>\n",
       "      <td>13085.0</td>\n",
       "      <td>United Kingdom</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>489434</td>\n",
       "      <td>22041</td>\n",
       "      <td>RECORD FRAME 7\" SINGLE SIZE</td>\n",
       "      <td>48</td>\n",
       "      <td>2009-12-01 07:45:00</td>\n",
       "      <td>2.10</td>\n",
       "      <td>13085.0</td>\n",
       "      <td>United Kingdom</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>489434</td>\n",
       "      <td>21232</td>\n",
       "      <td>STRAWBERRY CERAMIC TRINKET BOX</td>\n",
       "      <td>24</td>\n",
       "      <td>2009-12-01 07:45:00</td>\n",
       "      <td>1.25</td>\n",
       "      <td>13085.0</td>\n",
       "      <td>United Kingdom</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "  Invoice StockCode                          Description  Quantity  \\\n",
       "0  489434     85048  15CM CHRISTMAS GLASS BALL 20 LIGHTS        12   \n",
       "1  489434    79323P                   PINK CHERRY LIGHTS        12   \n",
       "2  489434    79323W                  WHITE CHERRY LIGHTS        12   \n",
       "3  489434     22041         RECORD FRAME 7\" SINGLE SIZE         48   \n",
       "4  489434     21232       STRAWBERRY CERAMIC TRINKET BOX        24   \n",
       "\n",
       "          InvoiceDate  Price  Customer ID         Country  \n",
       "0 2009-12-01 07:45:00   6.95      13085.0  United Kingdom  \n",
       "1 2009-12-01 07:45:00   6.75      13085.0  United Kingdom  \n",
       "2 2009-12-01 07:45:00   6.75      13085.0  United Kingdom  \n",
       "3 2009-12-01 07:45:00   2.10      13085.0  United Kingdom  \n",
       "4 2009-12-01 07:45:00   1.25      13085.0  United Kingdom  "
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# ============================================================\n",
    "# PROJECT: Consumer360 - Retail Analytics\n",
    "# WEEK 1: DATA CLEANING & PREPARATION\n",
    "#\n",
    "# OBJECTIVE:\n",
    "# 1. Load raw retail transaction data (Excel)\n",
    "# 2. Clean and standardize transactional records\n",
    "# 3. Handle missing / invalid values\n",
    "# 4. Prepare MySQL-ready clean dataset\n",
    "# ============================================================\n",
    "\n",
    "\n",
    "# -----------------------------\n",
    "# STEP 1: IMPORT REQUIRED LIBRARIES\n",
    "# -----------------------------\n",
    "# pandas is used for data loading, cleaning, and manipulation\n",
    "import pandas as pd\n",
    "\n",
    "\n",
    "# ------------------------------------------------------------\n",
    "# STEP 2: LOAD DATASET FROM LOCAL SYSTEM\n",
    "# ------------------------------------------------------------\n",
    "# Excel file path (stored locally on Windows system)\n",
    "\n",
    "file_path = r\"C:\\Users\\satya\\downloads\\online_retail_II.xlsx\"\n",
    "\n",
    "# Read Excel file into a pandas DataFrame\n",
    "df = pd.read_excel(file_path)\n",
    "\n",
    "# Verify dataset loading\n",
    "print(\"Raw dataset loaded successfully\")\n",
    "print(\"Raw dataset shape:\", df.shape)\n",
    "\n",
    "\n",
    "# ------------------------------------------------------------\n",
    "# STEP 3: INITIAL DATA INSPECTION\n",
    "# ------------------------------------------------------------\n",
    "# Display column names to understand data structure\n",
    "print(\"Columns in dataset:\")\n",
    "print(df.columns.tolist())\n",
    "\n",
    "# Preview first few records\n",
    "df.head()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "7e6e91c2-b8fc-473b-abf1-28800e6a4ccc",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "DataFrame columns: ['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'Price', 'Customer ID', 'Country']\n",
      "Cleaned dataset shape: (4312, 8)\n",
      "\n",
      "Null values after cleaning:\n",
      "Invoice        0\n",
      "StockCode      0\n",
      "Description    0\n",
      "Quantity       0\n",
      "InvoiceDate    0\n",
      "Price          0\n",
      "Customer ID    0\n",
      "Country        0\n",
      "dtype: int64\n",
      "<class 'pandas.core.frame.DataFrame'>\n",
      "RangeIndex: 4312 entries, 0 to 4311\n",
      "Data columns (total 8 columns):\n",
      " #   Column       Non-Null Count  Dtype  \n",
      "---  ------       --------------  -----  \n",
      " 0   Invoice      4312 non-null   object \n",
      " 1   StockCode    4312 non-null   object \n",
      " 2   Description  4312 non-null   object \n",
      " 3   Quantity     4312 non-null   int64  \n",
      " 4   InvoiceDate  4312 non-null   object \n",
      " 5   Price        4312 non-null   float64\n",
      " 6   Customer ID  4312 non-null   int64  \n",
      " 7   Country      4312 non-null   object \n",
      "dtypes: float64(1), int64(2), object(5)\n",
      "memory usage: 269.6+ KB\n",
      "\n",
      "Clean CSV file saved successfully at:\n",
      "C:\\Users\\satya\\downloads\\online_retail_clean.csv\n"
     ]
    }
   ],
   "source": [
    "# -----------------------------\n",
    "# STEP 4: DATA CLEANING\n",
    "# -----------------------------\n",
    "\n",
    "# Check available columns before proceeding\n",
    "print(\"\\nDataFrame columns:\", df.columns.tolist())\n",
    "\n",
    "# 1. Convert InvoiceDate to datetime (MySQL compatible)\n",
    "df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'], errors='coerce')\n",
    "\n",
    "df['InvoiceDate'] = df['InvoiceDate'].dt.strftime('%Y-%m-%d')\n",
    "\n",
    "# -----------------------------\n",
    "# Remove any remaining nulls in critical columns\n",
    "# -----------------------------\n",
    "critical_columns = ['Customer ID', 'InvoiceDate']\n",
    "df = df.dropna(subset=critical_columns)\n",
    "\n",
    "# 2. Remove rows with invalid or missing InvoiceDate\n",
    "df = df.dropna(subset=['InvoiceDate'])\n",
    "\n",
    "# 3. Remove cancelled / negative quantity transactions\n",
    "df = df[df['Quantity'] > 0]\n",
    "\n",
    "# 4. Remove invalid unit price values\n",
    "if 'Price' in df.columns:\n",
    "    df = df[df['Price'] > 0]\n",
    "else:\n",
    "    print(\"Warning: 'Price' column not found. Skipping unit price filtering.\")\n",
    "\n",
    "\n",
    "# 5. Cleaning  CustomerID column\n",
    "\n",
    "# S1. Strip leading/trailing spaces\n",
    "df['Customer ID'] = df['Customer ID'].astype(str).str.strip()\n",
    "\n",
    "# S2. Replace 'NaN' strings or empty strings with actual NaN\n",
    "# Fix for FutureWarning: Assign the result back to the column\n",
    "df['Customer ID'] = df['Customer ID'].replace(['', 'NaN', 'nan', None], pd.NA)\n",
    "\n",
    "# S3. Remove rows with missing CustomerID (optional)\n",
    "df = df.dropna(subset=['Customer ID'])\n",
    "\n",
    "# S5. Remove duplicates\n",
    "df = df.drop_duplicates(subset=['Customer ID'])\n",
    "\n",
    "# S6. Optionally, convert to integer\n",
    "# Fix: Convert to float first to handle string representations of floats (e.g., '13085.0'), then to int.\n",
    "df['Customer ID'] = df['Customer ID'].astype(float).astype(int)\n",
    "\n",
    "\n",
    "# 6. Reset index after cleaning\n",
    "df.reset_index(drop=True, inplace=True)\n",
    "\n",
    "print(\"Cleaned dataset shape:\", df.shape)\n",
    "\n",
    "\n",
    "# -----------------------------\n",
    "# STEP 5: DATA QUALITY CHECK\n",
    "# -----------------------------\n",
    "print(\"\\nNull values after cleaning:\")\n",
    "print(df.isnull().sum())\n",
    "\n",
    "df.info()\n",
    "\n",
    "\n",
    "# -----------------------------\n",
    "# STEP 6: EXPORT CLEAN DATA TO CSV\n",
    "# -----------------------------\n",
    "\n",
    "output_path = r\"C:\\Users\\satya\\downloads\\online_retail_clean.csv\"\n",
    "\n",
    "df.to_csv(output_path, index=False, encoding=\"utf-8\")\n",
    "\n",
    "print(\"\\nClean CSV file saved successfully at:\")\n",
    "print(output_path)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 40,
   "id": "12a3a0ec-76c9-4ac9-ae65-f61107a9a9e9",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: mysql-connector-python in c:\\users\\satya\\anaconda3\\lib\\site-packages (9.6.0)\n",
      "Requirement already satisfied: sqlalchemy in c:\\users\\satya\\anaconda3\\lib\\site-packages (2.0.43)\n",
      "Requirement already satisfied: pymysql in c:\\users\\satya\\anaconda3\\lib\\site-packages (1.1.2)\n",
      "Requirement already satisfied: greenlet>=1 in c:\\users\\satya\\anaconda3\\lib\\site-packages (from sqlalchemy) (3.2.4)\n",
      "Requirement already satisfied: typing-extensions>=4.6.0 in c:\\users\\satya\\anaconda3\\lib\\site-packages (from sqlalchemy) (4.15.0)\n",
      "Collecting mlxtend\n",
      "  Downloading mlxtend-0.24.0-py3-none-any.whl.metadata (7.3 kB)\n",
      "Requirement already satisfied: scipy>=1.16.3 in c:\\users\\satya\\anaconda3\\lib\\site-packages (from mlxtend) (1.16.3)\n",
      "Requirement already satisfied: numpy>=2.3.5 in c:\\users\\satya\\anaconda3\\lib\\site-packages (from mlxtend) (2.3.5)\n",
      "Requirement already satisfied: pandas>=2.3.3 in c:\\users\\satya\\anaconda3\\lib\\site-packages (from mlxtend) (2.3.3)\n",
      "Collecting scikit-learn>=1.8.0 (from mlxtend)\n",
      "  Downloading scikit_learn-1.8.0-cp313-cp313-win_amd64.whl.metadata (11 kB)\n",
      "Collecting matplotlib>=3.10.8 (from mlxtend)\n",
      "  Downloading matplotlib-3.10.8-cp313-cp313-win_amd64.whl.metadata (52 kB)\n",
      "Requirement already satisfied: joblib>=1.5.2 in c:\\users\\satya\\anaconda3\\lib\\site-packages (from mlxtend) (1.5.2)\n",
      "Requirement already satisfied: contourpy>=1.0.1 in c:\\users\\satya\\anaconda3\\lib\\site-packages (from matplotlib>=3.10.8->mlxtend) (1.3.3)\n",
      "Requirement already satisfied: cycler>=0.10 in c:\\users\\satya\\anaconda3\\lib\\site-packages (from matplotlib>=3.10.8->mlxtend) (0.11.0)\n",
      "Requirement already satisfied: fonttools>=4.22.0 in c:\\users\\satya\\anaconda3\\lib\\site-packages (from matplotlib>=3.10.8->mlxtend) (4.60.1)\n",
      "Requirement already satisfied: kiwisolver>=1.3.1 in c:\\users\\satya\\anaconda3\\lib\\site-packages (from matplotlib>=3.10.8->mlxtend) (1.4.9)\n",
      "Requirement already satisfied: packaging>=20.0 in c:\\users\\satya\\anaconda3\\lib\\site-packages (from matplotlib>=3.10.8->mlxtend) (25.0)\n",
      "Requirement already satisfied: pillow>=8 in c:\\users\\satya\\anaconda3\\lib\\site-packages (from matplotlib>=3.10.8->mlxtend) (12.0.0)\n",
      "Requirement already satisfied: pyparsing>=3 in c:\\users\\satya\\anaconda3\\lib\\site-packages (from matplotlib>=3.10.8->mlxtend) (3.2.5)\n",
      "Requirement already satisfied: python-dateutil>=2.7 in c:\\users\\satya\\anaconda3\\lib\\site-packages (from matplotlib>=3.10.8->mlxtend) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in c:\\users\\satya\\anaconda3\\lib\\site-packages (from pandas>=2.3.3->mlxtend) (2025.2)\n",
      "Requirement already satisfied: tzdata>=2022.7 in c:\\users\\satya\\anaconda3\\lib\\site-packages (from pandas>=2.3.3->mlxtend) (2025.2)\n",
      "Requirement already satisfied: six>=1.5 in c:\\users\\satya\\anaconda3\\lib\\site-packages (from python-dateutil>=2.7->matplotlib>=3.10.8->mlxtend) (1.17.0)\n",
      "Requirement already satisfied: threadpoolctl>=3.2.0 in c:\\users\\satya\\anaconda3\\lib\\site-packages (from scikit-learn>=1.8.0->mlxtend) (3.5.0)\n",
      "Downloading mlxtend-0.24.0-py3-none-any.whl (1.4 MB)\n",
      "   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--\n",
      "   ------- -------------------------------- 0.3/1.4 MB ? eta -:--:--\n",
      "   --------------- ------------------------ 0.5/1.4 MB 1.4 MB/s eta 0:00:01\n",
      "   ------------------------------ --------- 1.0/1.4 MB 1.8 MB/s eta 0:00:01\n",
      "   ---------------------------------------- 1.4/1.4 MB 1.7 MB/s  0:00:00\n",
      "Downloading matplotlib-3.10.8-cp313-cp313-win_amd64.whl (8.1 MB)\n",
      "   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--\n",
      "   - -------------------------------------- 0.3/8.1 MB ? eta -:--:--\n",
      "   ----- ---------------------------------- 1.0/8.1 MB 2.7 MB/s eta 0:00:03\n",
      "   ------- -------------------------------- 1.6/8.1 MB 2.8 MB/s eta 0:00:03\n",
      "   ---------- ----------------------------- 2.1/8.1 MB 2.6 MB/s eta 0:00:03\n",
      "   ----------- ---------------------------- 2.4/8.1 MB 2.4 MB/s eta 0:00:03\n",
      "   --------------- ------------------------ 3.1/8.1 MB 2.6 MB/s eta 0:00:02\n",
      "   ------------------- -------------------- 3.9/8.1 MB 2.8 MB/s eta 0:00:02\n",
      "   ----------------------- ---------------- 4.7/8.1 MB 2.9 MB/s eta 0:00:02\n",
      "   --------------------------- ------------ 5.5/8.1 MB 3.0 MB/s eta 0:00:01\n",
      "   ------------------------------ --------- 6.3/8.1 MB 3.1 MB/s eta 0:00:01\n",
      "   ------------------------------------ --- 7.3/8.1 MB 3.3 MB/s eta 0:00:01\n",
      "   ---------------------------------------- 8.1/8.1 MB 3.3 MB/s  0:00:02\n",
      "Downloading scikit_learn-1.8.0-cp313-cp313-win_amd64.whl (8.0 MB)\n",
      "   ---------------------------------------- 0.0/8.0 MB ? eta -:--:--\n",
      "   ----- ---------------------------------- 1.0/8.0 MB 5.1 MB/s eta 0:00:02\n",
      "   ---------- ----------------------------- 2.1/8.0 MB 5.3 MB/s eta 0:00:02\n",
      "   --------------- ------------------------ 3.1/8.0 MB 5.4 MB/s eta 0:00:01\n",
      "   ---------------------- ----------------- 4.5/8.0 MB 5.5 MB/s eta 0:00:01\n",
      "   --------------------------- ------------ 5.5/8.0 MB 5.5 MB/s eta 0:00:01\n",
      "   ---------------------------------- ----- 6.8/8.0 MB 5.5 MB/s eta 0:00:01\n",
      "   ---------------------------------------  7.9/8.0 MB 5.6 MB/s eta 0:00:01\n",
      "   ---------------------------------------- 8.0/8.0 MB 5.3 MB/s  0:00:01\n",
      "Installing collected packages: scikit-learn, matplotlib, mlxtend\n",
      "\n",
      "  Attempting uninstall: scikit-learn\n",
      "\n",
      "    Found existing installation: scikit-learn 1.7.2\n",
      "\n",
      "   ---------------------------------------- 0/3 [scikit-learn]\n",
      "   ---------------------------------------- 0/3 [scikit-learn]\n",
      "   ---------------------------------------- 0/3 [scikit-learn]\n",
      "    Uninstalling scikit-learn-1.7.2:\n",
      "   ---------------------------------------- 0/3 [scikit-learn]\n",
      "      Successfully uninstalled scikit-learn-1.7.2\n",
      "   ---------------------------------------- 0/3 [scikit-learn]\n",
      "   ---------------------------------------- 0/3 [scikit-learn]\n",
      "   ---------------------------------------- 0/3 [scikit-learn]\n",
      "   ---------------------------------------- 0/3 [scikit-learn]\n",
      "   ---------------------------------------- 0/3 [scikit-learn]\n",
      "   ---------------------------------------- 0/3 [scikit-learn]\n",
      "   ---------------------------------------- 0/3 [scikit-learn]\n",
      "   ---------------------------------------- 0/3 [scikit-learn]\n",
      "   ---------------------------------------- 0/3 [scikit-learn]\n",
      "   ---------------------------------------- 0/3 [scikit-learn]\n",
      "   ---------------------------------------- 0/3 [scikit-learn]\n",
      "   ---------------------------------------- 0/3 [scikit-learn]\n",
      "   ---------------------------------------- 0/3 [scikit-learn]\n",
      "   ---------------------------------------- 0/3 [scikit-learn]\n",
      "   ---------------------------------------- 0/3 [scikit-learn]\n",
      "   ---------------------------------------- 0/3 [scikit-learn]\n",
      "   ---------------------------------------- 0/3 [scikit-learn]\n",
      "   ---------------------------------------- 0/3 [scikit-learn]\n",
      "   ---------------------------------------- 0/3 [scikit-learn]\n",
      "   ---------------------------------------- 0/3 [scikit-learn]\n",
      "   ---------------------------------------- 0/3 [scikit-learn]\n",
      "   ---------------------------------------- 0/3 [scikit-learn]\n",
      "   ---------------------------------------- 0/3 [scikit-learn]\n",
      "   ---------------------------------------- 0/3 [scikit-learn]\n",
      "   ---------------------------------------- 0/3 [scikit-learn]\n",
      "   ---------------------------------------- 0/3 [scikit-learn]\n",
      "   ---------------------------------------- 0/3 [scikit-learn]\n",
      "   ---------------------------------------- 0/3 [scikit-learn]\n",
      "   ---------------------------------------- 0/3 [scikit-learn]\n",
      "   ---------------------------------------- 0/3 [scikit-learn]\n",
      "   ---------------------------------------- 0/3 [scikit-learn]\n",
      "   ---------------------------------------- 0/3 [scikit-learn]\n",
      "   ---------------------------------------- 0/3 [scikit-learn]\n",
      "   ---------------------------------------- 0/3 [scikit-learn]\n",
      "   ---------------------------------------- 0/3 [scikit-learn]\n",
      "   ---------------------------------------- 0/3 [scikit-learn]\n",
      "   ---------------------------------------- 0/3 [scikit-learn]\n",
      "   ---------------------------------------- 0/3 [scikit-learn]\n",
      "  Attempting uninstall: matplotlib\n",
      "   ---------------------------------------- 0/3 [scikit-learn]\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "    Found existing installation: matplotlib 3.10.6\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "    Uninstalling matplotlib-3.10.6:\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "      Successfully uninstalled matplotlib-3.10.6\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "   ------------- -------------------------- 1/3 [matplotlib]\n",
      "   -------------------------- ------------- 2/3 [mlxtend]\n",
      "   -------------------------- ------------- 2/3 [mlxtend]\n",
      "   -------------------------- ------------- 2/3 [mlxtend]\n",
      "   -------------------------- ------------- 2/3 [mlxtend]\n",
      "   ---------------------------------------- 3/3 [mlxtend]\n",
      "\n",
      "Successfully installed matplotlib-3.10.8 mlxtend-0.24.0 scikit-learn-1.8.0\n"
     ]
    }
   ],
   "source": [
    "# Install the MySQL connector\n",
    "!pip install mysql-connector-python\n",
    "!pip install sqlalchemy pymysql\n",
    "!pip install mlxtend\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 50,
   "id": "afb5bca9-2121-4066-87c8-173281fa2715",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "MySQL connection established successfully\n",
      "Data loaded successfully\n",
      "RFM Table Shape: (4311, 4)\n",
      "Sales Table Shape: (4311, 8)\n",
      "\n",
      "Customer Segment Distribution:\n",
      "Segment\n",
      "Potential Customers    1892\n",
      "Loyal Customers        1507\n",
      "At Risk                 539\n",
      "Champions               286\n",
      "Lost Customers           87\n",
      "Name: count, dtype: int64\n",
      "\n",
      "Starting Market Basket Analysis...\n",
      "Total invoices: 4311\n",
      "Average items per invoice: 1.0\n",
      "Max items in invoice: 1\n",
      "Invoices with >1 item: 0\n",
      "Basket shape: (4311, 1696)\n",
      "Frequent Itemsets Found: 60\n",
      "    support   itemsets\n",
      "0  0.002784  (15056BL)\n",
      "1  0.002784    (20685)\n",
      "2  0.002784    (20712)\n",
      "3  0.002552    (20725)\n",
      "4  0.002088    (20727)\n",
      "Rules Generated: 0\n",
      "No association rules found.\n",
      "\n",
      "Starting Cohort Analysis...\n",
      "Cohort Table Created Successfully\n",
      "CohortIndex CohortMonth      1\n",
      "0               2009-12  955.0\n",
      "1               2010-01  383.0\n",
      "2               2010-02  373.0\n",
      "3               2010-03  443.0\n",
      "4               2010-04  294.0\n",
      "\n",
      " WEEK 2 COMPLETED SUCCESSFULLY\n"
     ]
    }
   ],
   "source": [
    "# ============================================================\n",
    "# WEEK 2: RFM SCORING & CUSTOMER SEGMENTATION\n",
    "#\n",
    "# OBJECTIVE:\n",
    "# 1. Connect to MySQL database\n",
    "# 2. Load RFM base metrics (Recency, Frequency, Monetary)\n",
    "# 3. Apply RFM scoring using quantiles (1–5 scale)\n",
    "# 4. Calculate total RFM score\n",
    "# 5. Segment customers based on RFM score\n",
    "# 6. Export final customer segments\n",
    "# ============================================================\n",
    "\n",
    "\n",
    "# ------------------------------------------------------------\n",
    "# STEP 1: IMPORT REQUIRED LIBRARIES\n",
    "# ------------------------------------------------------------\n",
    "import pandas as pd\n",
    "import mysql.connector\n",
    "from sqlalchemy import create_engine\n",
    "from sqlalchemy.engine import URL\n",
    "from mlxtend.frequent_patterns import apriori, association_rules\n",
    "\n",
    "\n",
    "# ------------------------------------------------------------\n",
    "# STEP 2: CONNECT TO MYSQL DATABASE\n",
    "# ------------------------------------------------------------\n",
    "username = \"root\"\n",
    "password = \"Jyothi@2945\"   \n",
    "host = \"localhost\"\n",
    "database = \"retail_db\"\n",
    "\n",
    "# Create URL object (handles special characters automatically)\n",
    "connection_url = URL.create(\n",
    "    drivername=\"mysql+pymysql\",\n",
    "    username=username,\n",
    "    password=password,\n",
    "    host=host,\n",
    "    database=database,\n",
    ")\n",
    "\n",
    "engine = create_engine(connection_url)\n",
    "\n",
    "print(\"MySQL connection established successfully\")\n",
    "\n",
    "\n",
    "# ------------------------------------------------------------\n",
    "# STEP 3: LOAD RFM BASE DATA FROM MYSQL\n",
    "# ------------------------------------------------------------\n",
    "query_rfm = \"SELECT * FROM RFM_Table\"\n",
    "query_sales = \"SELECT CustomerID, InvoiceDate, SalesID,InvoiceNo, Quantity,Price, Stockcode, Sales_Amount FROM fact_sales\"\n",
    "\n",
    "\n",
    "rfm = pd.read_sql(query_rfm, engine)\n",
    "sales= pd.read_sql(query_sales,engine)\n",
    "\n",
    "print(\"Data loaded successfully\")\n",
    "print(\"RFM Table Shape:\", rfm.shape)\n",
    "print(\"Sales Table Shape:\", sales.shape)\n",
    "\n",
    "rfm.head()\n",
    "sales.head()\n",
    "\n",
    "# ============================================================\n",
    "# PART 1 – RFM CALCULATION\n",
    "# ============================================================\n",
    "\n",
    "# ------------------------------------------------------------\n",
    "# STEP 4: CREATE SNAPSHOT DATE\n",
    "# ------------------------------------------------------------\n",
    "snapshot_date = sales[\"InvoiceDate\"].max() + pd.Timedelta(days=1)\n",
    "\n",
    "\n",
    "# ------------------------------------------------------------\n",
    "# STEP 5: CALCULATE RFM METRICS\n",
    "# ------------------------------------------------------------\n",
    "rfm_seg = sales.groupby(\"CustomerID\").agg({\n",
    "    \"InvoiceDate\": lambda x: (snapshot_date - x.max()).days,\n",
    "    \"InvoiceNo\": \"count\",\n",
    "    \"Sales_Amount\": \"sum\"\n",
    "}).reset_index()\n",
    "\n",
    "rfm.columns = [\"CustomerID\", \"Recency\", \"Frequency\", \"Monetary\"]\n",
    "\n",
    "\n",
    "# ------------------------------------------------------------\n",
    "# STEP 6: RFM SCORING USING QUANTILES (1–5 SCALE)\n",
    "# ------------------------------------------------------------\n",
    "# Use ranking first to avoid duplicate quantile issues\n",
    "\n",
    "rfm['R_rank'] = rfm['Recency'].rank(method='first')\n",
    "rfm['F_rank'] = rfm['Frequency'].rank(method='first')\n",
    "rfm['M_rank'] = rfm['Monetary'].rank(method='first')\n",
    "\n",
    "# Recency: lower value = better customer\n",
    "# Hence, reverse the scoring (5 = most recent)\n",
    "rfm['R_Score'] = pd.qcut(rfm['R_rank'], 5, labels=[5,4,3,2,1])\n",
    "\n",
    "\n",
    "# Frequency: higher value = better customer\n",
    "rfm['F_Score'] = pd.qcut(rfm['F_rank'],5, labels=[1,2,3,4,5])\n",
    "\n",
    "# Monetary: higher value = better customer\n",
    "rfm['M_Score'] = pd.qcut(rfm['M_rank'],5, labels=[1,2,3,4,5])\n",
    "\n",
    "\n",
    "# ------------------------------------------------------------\n",
    "# STEP 7: CALCULATE TOTAL RFM SCORE\n",
    "# ------------------------------------------------------------\n",
    "# Convert individual R, F, M scores to integers\n",
    "# Sum them to get final RFM score\n",
    "rfm['RFM_Score'] = (\n",
    "    rfm['R_Score'].astype(int) +\n",
    "    rfm['F_Score'].astype(int) +\n",
    "    rfm['M_Score'].astype(int)\n",
    ")\n",
    "\n",
    "\n",
    "# ------------------------------------------------------------\n",
    "# STEP 8: CUSTOMER SEGMENTATION LOGIC\n",
    "# ------------------------------------------------------------\n",
    "# Segment customers based on total RFM score\n",
    "def segment_customer(score):\n",
    "    if score >= 13:\n",
    "        return \"Champions\"\n",
    "    elif score >= 10:\n",
    "        return \"Loyal Customers\"\n",
    "    elif score >= 7:\n",
    "        return \"Potential Customers\"\n",
    "    elif score >= 5:\n",
    "        return \"At Risk\"\n",
    "    else:\n",
    "        return \"Lost Customers\"\n",
    "\n",
    "# Apply segmentation logic\n",
    "rfm['Segment'] = rfm['RFM_Score'].apply(segment_customer)\n",
    "\n",
    "\n",
    "# ------------------------------------------------------------\n",
    "# STEP 9: SEGMENT DISTRIBUTION CHECK\n",
    "# ------------------------------------------------------------\n",
    "print(\"\\nCustomer Segment Distribution:\")\n",
    "print(rfm['Segment'].value_counts())\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# PART 2 – MARKET BASKET ANALYSIS\n",
    "# ============================================================\n",
    "\n",
    "print(\"\\nStarting Market Basket Analysis...\")\n",
    "\n",
    "# ------------------------------------------------------------\n",
    "# Check Transaction Structure\n",
    "# ------------------------------------------------------------\n",
    "\n",
    "items_per_invoice = sales.groupby(\"InvoiceNo\")[\"Stockcode\"].nunique()\n",
    "\n",
    "print(\"Total invoices:\", sales[\"InvoiceNo\"].nunique())\n",
    "print(\"Average items per invoice:\", round(items_per_invoice.mean(), 2))\n",
    "print(\"Max items in invoice:\", items_per_invoice.max())\n",
    "print(\"Invoices with >1 item:\", (items_per_invoice > 1).sum())\n",
    "\n",
    "# ------------------------------------------------------------\n",
    "# Create Basket Matrix\n",
    "# ------------------------------------------------------------\n",
    "\n",
    "basket = (\n",
    "    sales.groupby([\"InvoiceNo\", \"Stockcode\"])[\"Quantity\"]\n",
    "    .sum()\n",
    "    .unstack()\n",
    "    .fillna(0)\n",
    ")\n",
    "\n",
    "# Convert to boolean (IMPORTANT)\n",
    "basket = basket > 0\n",
    "\n",
    "print(\"Basket shape:\", basket.shape)\n",
    "\n",
    "# ------------------------------------------------------------\n",
    "# Apply Apriori\n",
    "# ------------------------------------------------------------\n",
    "\n",
    "frequent_items = apriori(\n",
    "    basket,\n",
    "    min_support=0.002,   # Very low due to sparse data\n",
    "    use_colnames=True\n",
    ")\n",
    "\n",
    "print(\"Frequent Itemsets Found:\", len(frequent_items))\n",
    "\n",
    "# Show frequent itemsets\n",
    "print(frequent_items.head())\n",
    "\n",
    "# ------------------------------------------------------------\n",
    "# Generate Association Rules\n",
    "# ------------------------------------------------------------\n",
    "\n",
    "if frequent_items.empty:\n",
    "    print(\"No frequent itemsets found. Dataset may not support MBA.\")\n",
    "else:\n",
    "    rules = association_rules(\n",
    "        frequent_items,\n",
    "        metric=\"confidence\",\n",
    "        min_threshold=0.05\n",
    "    )\n",
    "\n",
    "    print(\"Rules Generated:\", len(rules))\n",
    "\n",
    "    if rules.empty:\n",
    "        print(\"No association rules found.\")\n",
    "    else:\n",
    "        rules = rules.sort_values(by=\"confidence\", ascending=False)\n",
    "\n",
    "        print(\"\\nTop Market Basket Rules:\")\n",
    "        print(rules.head(10)[[\n",
    "            \"antecedents\",\n",
    "            \"consequents\",\n",
    "            \"support\",\n",
    "            \"confidence\",\n",
    "            \"lift\"\n",
    "        ]])\n",
    "\n",
    "rules[\"antecedents\"] = rules[\"antecedents\"].astype(str)\n",
    "rules[\"consequents\"] = rules[\"consequents\"].astype(str)\n",
    "\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# PART 3 – COHORT ANALYSIS\n",
    "# ============================================================\n",
    "\n",
    "print(\"\\nStarting Cohort Analysis...\")\n",
    "\n",
    "# Create Invoice Month\n",
    "sales[\"InvoiceMonth\"] = sales[\"InvoiceDate\"].dt.to_period(\"M\")\n",
    "\n",
    "# First Purchase Month per Customer\n",
    "sales[\"CohortMonth\"] = sales.groupby(\"CustomerID\")[\"InvoiceDate\"] \\\n",
    "    .transform(\"min\") \\\n",
    "    .dt.to_period(\"M\")\n",
    "\n",
    "# Create Cohort Index\n",
    "def month_diff(d1, d2):\n",
    "    return (d1.year - d2.year) * 12 + (d1.month - d2.month)\n",
    "\n",
    "sales[\"CohortIndex\"] = (\n",
    "    sales[\"InvoiceMonth\"].dt.year - sales[\"CohortMonth\"].dt.year\n",
    ") * 12 + (\n",
    "    sales[\"InvoiceMonth\"].dt.month - sales[\"CohortMonth\"].dt.month\n",
    ") + 1\n",
    "\n",
    "# Build Cohort Table \n",
    "cohort_data = sales.groupby(\n",
    "    [\"CohortMonth\", \"CohortIndex\"]\n",
    ")[\"CustomerID\"].nunique().reset_index()\n",
    "\n",
    "cohort_pivot = cohort_data.pivot_table(\n",
    "    index=\"CohortMonth\",\n",
    "    columns=\"CohortIndex\",\n",
    "    values=\"CustomerID\"\n",
    ")\n",
    "cohort_pivot = cohort_pivot.reset_index()\n",
    "cohort_pivot[\"CohortMonth\"] = cohort_pivot[\"CohortMonth\"].astype(str)\n",
    "\n",
    "print(\"Cohort Table Created Successfully\")\n",
    "print(cohort_pivot.head())\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "# ------------------------------------------------------------\n",
    "#  EXPORT FINAL RFM RESULTS\n",
    "# ------------------------------------------------------------\n",
    "# Save results to CSV for reporting / Power BI\n",
    "\n",
    "rfm.to_sql(\"rfm_customer_segments\", engine, if_exists=\"replace\", index=False)\n",
    "rules.to_sql(\"market_basket_rules\", engine, if_exists=\"replace\", index=False)\n",
    "cohort_pivot.to_sql(\"cohort_analysis\", engine, if_exists=\"replace\",index=False)\n",
    "\n",
    "print(\"\\n WEEK 2 COMPLETED SUCCESSFULLY\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0f76b899-39a0-4f8c-bb61-77e3a57cce62",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
